using '../main.bicep'

param resourceGroupName = 'rg-yone-containerapps-cicd'
param name = 'ca-yone-containerapps-cicd'
param userAssignedManagedIdentityId = '/subscriptions/6b5a0a79-da53-4c9f-92db-40a73a4a68d3/resourcegroups/rg-yone-containerapps-cicd/providers/microsoft.managedidentity/userassignedidentities/id-yone-containerapps-cicd'
param environmentId = '/subscriptions/6b5a0a79-da53-4c9f-92db-40a73a4a68d3/resourceGroups/rg-yone-containerapps-cicd/providers/Microsoft.App/managedEnvironments/cae-yone-containerapps-cicd'
param acrName = 'acryonetest'
param image = 'acryonetest.azurecr.io/helloworld:latest'
param containerName = 'helloworld-container'
param cpu = '0.25'
param memory = '0.5Gi'
