type: Microsoft.App/containerApps
properties:
  template:
    containers:
      - image: acryonetest.azurecr.io/helloworld:d2ed6f8
        name: helloworld-container
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 3
