name: Create pull request
on:
  repository_dispatch:

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GITHUB_NAME: github-actions[bot]

    steps:
      - uses: actions/checkout@main

      - name: Push
        run: |
          git remote set-url origin https://github-actions:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}
          git config user.email ${{ env.GITHUB_MAIL }}
          git config user.name ${{ env.GITHUB_NAME }}
          echo "Hello GitHub Actions!" >> hello.txt
          git add .
          git commit -m "generated"
          git push origin main

      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "test" \
            --body ""
          
