name: Create pull request
on:
  repository_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@main

      - name: Push
        run: |
          echo "Hello GitHub Actions!" > hello.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "test" \
            --body ""
          
