name: Create pull request
on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  get_env_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.environments }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: |
          env_list=$(curl --location https://api.github.com/repos/${{ github.repository }}/environments --header 'Authorization: Bearer ${{ secrets.GH_TOKEN }}' | jq -r '[.environments[].name]')
          echo environments=$(echo $env_list | jq -c .) >> $GITHUB_OUTPUT

  create-pull-request:
    runs-on: ubuntu-latest
    needs: get_env_matrix
    strategy:
      matrix:
        value: ${{ fromJson(needs.get_env_matrix.outputs.matrix) }}

    env:
      GH_TOKEN: ${{ github.token }}
      GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GITHUB_NAME: github-actions[bot]

    steps:
      - uses: actions/checkout@v4

      - name: Set env head branch (dev)
        if: ${{ startsWith(matrix.value, 'dev') }}
        run: |
          echo "head_branch=dev/${{ matrix.value }}-${{ github.event.client_payload.sha_short }}" >> $GITHUB_ENV

      - name: Set env head branch (release)
        if: ${{ !startsWith(matrix.value, 'dev') }}
        run: |
          echo "head_branch=release/${{ matrix.value }}-${{ github.event.client_payload.sha_short }}" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          git switch -c ${{ env.head_branch }}
          git push -u origin ${{ env.head_branch }}

      - name: Update container image
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git config user.email ${{ env.GITHUB_MAIL }}
          git config user.name ${{ env.GITHUB_NAME }}
          cd manifests/app1
          yq -r '.properties.template.containers[0].image|="${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.event.client_payload.sha_short }}"' ${{ matrix.value }}.yml > tmp && mv tmp ${{ matrix.value }}.yml
          git add .
          git commit -m "Update container image to ${{ github.event.client_payload.sha_short }}"
          git push origin ${{ env.head_branch }}

      - name: Create pull request
        run: |
          echo pr_url=$(gh pr create --base main --head ${{ env.head_branch }} --title "Update ${{ matrix.value }} container image to ${{ github.event.client_payload.sha_short }}" --fill) >> $GITHUB_ENV

      - name: Merge pull request (only dev)
        if: ${{ startsWith(matrix.value, 'dev') }}
        run: |
          gh pr merge --merge --auto ${{ env.pr_url }}
