name: Create pull request
on:
  repository_dispatch:

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GITHUB_NAME: github-actions[bot]

    steps:
      - uses: actions/checkout@main

      - name: Push
        run: |
          echo "Hello GitHub Actions!" > hello.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "test" \
            --body ""
          
