name: Create pull request
on:
  repository_dispatch:

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GITHUB_NAME: github-actions[bot]

    steps:
      - uses: actions/checkout@v4

      - name: Set current datetime
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "current_datetime=$(date + '%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Set head branch name
        run: |
          echo "head_branch=ci-${{ github.event.client_payload.sha_short }}-${{ env.current_datetime }}" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          git switch -c ${{ env.head_branch }}
          git push -u origin ${{ env.head_branch }}

      - name: Push
        run: |
          git remote set-url origin https://github-actions:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}
          git config user.email ${{ env.GITHUB_MAIL }}
          git config user.name ${{ env.GITHUB_NAME }}
          echo "Hello GitHub Actions!" >> hello.txt
          git add .
          git commit -m "generated"
          git push origin ${{ env.head_branch }}

      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head ${{ env.head_branch }} \
            --title "test" \
            --body ""
          
