name: Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: az containerapp update
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --resource-group rg-yone-containerapps-cicd \
              --name ca-yone-containerapps-cicd \
              --yaml manifests/app1/params/dev1.yml
