name: Deploy
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  set_environment:
      runs-on: ubuntu-latest
      outputs:
          env_name: ${{ steps.set_outputs.outputs.env_name }}
      if: github.event.pull_request.merged == true
      steps:
          - uses: winterjung/split@v2
            id: split
            with:
              msg: ${{ github.head_ref }}
              separator: /

          - id: set_outputs
            name: Set outputs
            run: |
              echo "env_name=${{ steps.split.outputs._1 }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: set_environment
    environment:
      name: ${{ needs.set_environment.outputs.env_name }}
      url: https://${{ steps.get_ca_fqdn.outputs.ca_fqdn }}
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: az containerapp update
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
              --name ${{ vars.CONTAINER_APP_NAME }} \
              --yaml manifests/app1/${{ needs.set_environment.outputs.env_name }}.yml

      - name: Get FQDN
        id: get_ca_fqdn
        run: |
          h=$(az containerapp show \
                --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
                --name ${{ vars.CONTAINER_APP_NAME }} \
                --query properties.configuration.ingress.fqdn \
              | tr -d '"')
          echo ca_fqdn=$h >> $GITHUB_OUTPUT
